#!/usr/bin/env python3
"""Central Neural Backend - Single source of truth"""
import os, json, pickle, hashlib
from pathlib import Path
from datetime import datetime

class CentralNeuralBackend:
    def __init__(self, root_dir="/home/popic/GhostGoat"):
        self.root_dir = root_dir
        self.backend_dir = os.path.join(root_dir, '.backend')
        self.graph_db = os.path.join(self.backend_dir, 'knowledge_graph.pkl')
        self.registry_db = os.path.join(self.backend_dir, 'file_registry.json')
        self.agents_db = os.path.join(self.backend_dir, 'agents.json')
        self.knowledge_graph = {}
        self.file_registry = {}
        self.agent_registry = {}
        self._initialize()
    
    def _initialize(self):
        os.makedirs(self.backend_dir, exist_ok=True)
        os.makedirs(os.path.join(self.backend_dir, 'agents'), exist_ok=True)
        self._load_state()
        print(f"✓ Central backend: {self.backend_dir}")
    
    def _load_state(self):
        if os.path.exists(self.graph_db):
            with open(self.graph_db, 'rb') as f:
                self.knowledge_graph = pickle.load(f)
        if os.path.exists(self.registry_db):
            with open(self.registry_db, 'r') as f:
                self.file_registry = json.load(f)
        if os.path.exists(self.agents_db):
            with open(self.agents_db, 'r') as f:
                self.agent_registry = json.load(f)
    
    def _save_state(self):
        with open(self.graph_db, 'wb') as f:
            pickle.dump(self.knowledge_graph, f)
        with open(self.registry_db, 'w') as f:
            json.dump(self.file_registry, f, indent=2)
        with open(self.agents_db, 'w') as f:
            json.dump(self.agent_registry, f, indent=2)
    
    def index_file(self, filepath):
        try:
            stat = os.stat(filepath)
            self.file_registry[filepath] = {
                'path': filepath,
                'size': stat.st_size,
                'modified': datetime.fromtimestamp(stat.st_mtime).isoformat(),
                'extension': Path(filepath).suffix,
                'hash': hashlib.sha256(open(filepath, 'rb').read()).hexdigest()[:16]
            }
            self.knowledge_graph[filepath] = {
                'indexed_at': datetime.now().isoformat()
            }
            self._save_state()
        except Exception as e:
            print(f"⚠ Error indexing {filepath}: {e}")
    
    def register_agent(self, folder_path):
        agent_id = hashlib.md5(folder_path.encode()).hexdigest()[:8]
        self.agent_registry[agent_id] = {
            'folder': folder_path,
            'created': datetime.now().isoformat(),
            'last_updated': datetime.now().isoformat()
        }
        self._save_state()
        return agent_id
    
    def get_folder_context(self, folder_path):
        return {k: v for k, v in self.file_registry.items() if k.startswith(folder_path)}

def scan_and_generate_agents(root_dir="/home/popic/GhostGoat"):
    backend = CentralNeuralBackend(root_dir)
    
    exclude_dirs = {'.git', '__pycache__', 'node_modules', '.venv', 'venv', 'node_modules', '.backend', 'vendor'}
    extensions = {'.py', '.js', '.json', '.txt', '.md', '.yaml', '.yml', '.toml', '.html', '.css'}
    
    folders_with_files = set()
    
    for root, dirs, files in os.walk(root_dir):
        dirs[:] = [d for d in dirs if d not in exclude_dirs]
        
        for filename in files:
            filepath = os.path.join(root, filename)
            if filename == 'AGENT.md' or filename.startswith('.'):
                continue
            if extensions and Path(filepath).suffix not in extensions and not filename.endswith('.py'):
                continue
            
            backend.index_file(filepath)
            folders_with_files.add(root)
    
    print(f"✓ Indexed {len(backend.file_registry)} files in {len(folders_with_files)} folders")
    
    for folder in sorted(folders_with_files):
        generate_agent_file(folder, backend)
    
    return backend

def generate_agent_file(folder_path, backend):
    folder_name = os.path.basename(folder_path)
    agent_file = os.path.join(folder_path, 'AGENT.md')
    
    files = backend.get_folder_context(folder_path)
    
    content = f"""# 🤖 AGENT - {folder_name}

**Last Updated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## 📁 Files ({len(files)})

"""
    for f, m in list(files.items())[:20]:
        rel = os.path.relpath(f, folder_path)
        content += f"- `{rel}` ({m.get('size', 0)} bytes)\n"
    
    if len(files) > 20:
        content += f"\n... and {len(files) - 20} more\n"
    
    content += f"\n---\n*Auto-generated by Central Neural Backend*"
    
    with open(agent_file, 'w') as f:
        f.write(content)
    
    backend.register_agent(folder_path)

if __name__ == "__main__":
    print("🔍 Scanning GhostGoat...")
    backend = scan_and_generate_agents()
    print("✓ Done!")