#!/usr/bin/env python3
"""
GhostGoat + GFS v5 — Full Telegram Integration
Numeric keys + Binary core + Living AGENT.md System
"""

from pathlib import Path
from collections import defaultdict
import os, sys
from datetime import datetime
from typing import Optional

# =============================================================================
# GFS v5 CORE
# =============================================================================

TYPE_MAP = {
    0: ("py", "python", "execute"),
    1: ("json", "json", "parse"),
    10: ("yaml", "yaml", "parse"),
    11: ("md", "markdown", "render"),
    20: ("sh", "shell", "execute"),
    30: ("cpp", "cpp", "compile"),
    99: ("cor", "meta", "system"),
}

ROLE_MAP = {0: "orchestrator", 1: "tool", 10: "config", 11: "data", 99: "meta"}
TIER_MAP = {0: "core", 1: "plugin", 10: "sandbox", 11: "archive"}

def encode_filename(t: int, r: int, i: int, s: int) -> str:
    return f"{t:02d}.{r:02d}.{i:02d}.{s:03d}"

class GFSRegistry:
    def __init__(self):
        self.entries = {}
    
    def register(self, t: int, r: int, i: int, s: int, description: str = "", tags=None):
        fname = encode_filename(t, r, i, s)
        data = {
            "filename": fname,
            "key_int": (t << 40) | (r << 32) | (i << 24) | s,
            "type_id": t, "role_id": r, "tier_id": i, "seq": s,
            "description": description,
            "tags": tags or []
        }
        self.entries[fname] = data
        return data
    
    def query_in_folder(self, folder: str):
        folder = str(Path(folder).resolve())
        return [e for e in self.entries.values() 
                if str(Path(e["filename"]).parent).startswith(folder)]

class GFSFolderAgent:
    def __init__(self, folder_path: str, gfs: GFSRegistry):
        self.folder_path = Path(folder_path).resolve()
        self.gfs = gfs
        self.agent_file = self.folder_path / "AGENT.md"
    
    def generate(self):
        files = self.gfs.query_in_folder(str(self.folder_path))
        content = self._build_content(files)
        self.agent_file.write_text(content, encoding='utf-8')
        return f"Updated {self.agent_file.relative_to(Path.cwd())}"
    
    def _build_content(self, files):
        ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        name = self.folder_path.name or "root"
        content = f"""# 🤖 AGENT — {name}

**Auto-generated by GhostGoat + GFS v5**  
**Updated:** {ts}  
**Path:** `{self.folder_path}`

---

## 📁 Files ({len(files)})

"""
        by_type = defaultdict(list)
        for f in files:
            by_type[f['type_id']].append(f)
        
        for tid, fs in sorted(by_type.items()):
            content += f"\n### {fs[0].get('handler','UNKNOWN').upper()} Files ({len(fs)})\n\n"
            for f in sorted(fs, key=lambda x: x['filename']):
                content += f"- `{f['filename']}` — {f.get('description','')}\n"
        
        content += f"""

---

## 🌐 GFS Status
**Total files tracked:** {len(self.gfs.entries)}
**System is alive.**
"""
        return content

class GhostGoatGFS:
    def __init__(self, root_dir: Optional[str] = None):
        self.root_dir = Path(root_dir or ".")
        self.gfs = GFSRegistry()
        self._seed_core_files()
    
    def _seed_core_files(self):
        self.gfs.register(0, 0, 0, 0, "ADAP main orchestrator")
        self.gfs.register(0, 1, 0, 0, "GhostGoat secure bridge")
        self.gfs.register(1, 10, 0, 0, "Quantum config")
    
    def update_all_agents(self) -> str:
        folders = set()
        for root, _, files in os.walk(self.root_dir):
            if any(f.endswith(('.py','.json','.yaml','.md','.sh','.cpp')) for f in files):
                folders.add(root)
        
        for folder in sorted(folders):
            GFSFolderAgent(folder, self.gfs).generate()
        return f"✅ Updated {len(folders)} AGENT.md files"
    
    def dispatch_command(self, cmd: str, arg: Optional[str] = None) -> str:
        cmd = cmd.lower().strip()
        if cmd in ["update", "refresh"]:
            return self.update_all_agents()
        elif cmd in ["status", "help"]:
            return "🛠️ /gfs update — Refresh all AGENT.md\n/gfs status — System status"
        return "Unknown command. Try /gfs update"

if __name__ == "__main__":
    gg = GhostGoatGFS()
    if len(sys.argv) > 1 and sys.argv[1] in ["update", "refresh"]:
        print(gg.update_all_agents())
    else:
        print("GhostGoat GFS v5 Ready → Run: python ghostgoat_gfs_v5.py update")
