"""
Folder Agent
=============

Each FolderAgent owns one AGENT.md file.
It auto-populates with:
  - All files in the folder (type-grouped)
  - Live stats from CentralNeuralBackend
  - A working OrdinanceClient snippet
  - NeuroGraph neighbour context (which other folders link here)
"""
from __future__ import annotations

import os
from collections import defaultdict
from datetime import datetime
from typing import Optional

from core.ordinance.central_backend import CentralNeuralBackend


class FolderAgent:
    """Generates and refreshes AGENT.md for one folder."""

    def __init__(self, folder_path: str, backend: CentralNeuralBackend):
        self.folder_path = folder_path
        self.backend     = backend
        self.agent_file  = os.path.join(folder_path, "AGENT.md")
        self.agent_id: Optional[str] = None

    # ── public API ─────────────────────────────────────────────────────────────

    def generate(self):
        """Write (or overwrite) AGENT.md for this folder."""
        # Register first so agent_id is available when building content
        self.agent_id = self.backend.register_agent(
            self.folder_path, self.agent_file
        )
        context = self.backend.get_folder_context(self.folder_path)
        content = self._build_content(context)

        with open(self.agent_file, "w") as f:
            f.write(content)

    update = generate   # alias

    # ── content builder ────────────────────────────────────────────────────────

    def _build_content(self, folder_files: dict) -> str:
        folder_name = os.path.basename(self.folder_path)
        rel_path    = os.path.relpath(self.folder_path,
                                      self.backend.root_dir)
        timestamp   = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        root_rel    = os.path.relpath(self.backend.root_dir, self.folder_path)

        # ── group files by extension ──────────────────────────────────────────
        by_ext: dict = defaultdict(list)
        for rel, meta in folder_files.items():
            by_ext[meta.get("extension", "")].append((rel, meta))

        files_section = ""
        for ext in sorted(by_ext):
            label = ext if ext else "(no extension)"
            files_section += f"\n#### `{label}` ({len(by_ext[ext])} files)\n\n"
            for rel, meta in sorted(by_ext[ext]):
                size     = meta.get("size", 0)
                size_str = (f"{size/1024:.1f} KB" if size > 1024
                            else f"{size} B")
                modified = meta.get("modified", "")[:10]
                files_section += (
                    f"- **`{rel}`** — {size_str}, modified {modified}\n"
                )

        total_size = sum(m.get("size", 0) for m in folder_files.values())
        size_str   = (f"{total_size/1024/1024:.2f} MB" if total_size > 1_048_576
                      else f"{total_size/1024:.1f} KB")

        # ── NeuroGraph neighbours ─────────────────────────────────────────────
        neighbours_section = ""
        try:
            ng      = self.backend._ng
            aid     = f"agent:{self.agent_id or 'pending'}"
            context_data = ng.get_context(aid, radius=2, kinds=["agent"]) if ng else {}
            if context_data:
                neighbours_section = "\n### Connected Folders\n"
                for node_id, data in list(context_data.items())[:8]:
                    neighbours_section += f"- `{data.get('folder', node_id)}`\n"
        except Exception:
            pass

        return f"""\
# AGENT — `{folder_name}`

> Auto-generated folder agent. **Do not edit manually** — regenerated on every scan.

| Field | Value |
|---|---|
| **Folder** | `{rel_path}` |
| **Agent ID** | `{self.agent_id or 'pending'}` |
| **Last Updated** | `{timestamp}` |
| **Files Tracked** | `{len(folder_files)}` |
| **Total Size** | `{size_str}` |
| **Neural Backend** | `{root_rel}/.backend/` |

---

## Files in this Folder
{files_section}
---

## Statistics

| Metric | Value |
|---|---|
| Files | {len(folder_files)} |
| Size | {size_str} |
| Types | {len(by_ext)} |
{neighbours_section}
---

## Neural Network Connection

This agent is part of GhostGoat's **Central Ordinance System**.
All agents share one neural backend at `.backend/`.

### Query this folder's context

```python
from core.ordinance.ordinance_client import OrdinanceClient

client = OrdinanceClient()

# All files in this folder
ctx = client.get_folder_context("{self.folder_path}")

# Full-text search across all folders
results = client.search("your query")

# This agent's neighbours in the knowledge graph
neighbours = client.get_neighbours("{self.agent_id or 'pending'}")
```

---

*Generated by GhostGoat Ordinance System — Central Neural Backend*
*Scan time: {timestamp}*
"""
